autocomplete-python/autocomplete-python

lib/main.coffee
lib/provider.coffee

Be more friendly looking for python executable

---

lib/completion.py

Python 2 compatible version of #36

fix bug when current file is in non-english path

---

README.md

This provides (at least) two benefits:
- Correct choice of python/python3/pypy/pypy3 interpreter.
- Completion for third-party packages.

Fix #56 - Document running Atom from an activated virtualenv

---

lib/main.coffee
lib/provider.coffee

This include the option to choose the python executable that you want, like python3, python3.4, etc.
There a reference for this in #26 and more recently #40 .

Python executable configuration

---

lib/completion.py
lib/definitions-view.coffee
lib/provider.coffee
package.json

Now with a select box that allows user to select the symbol to jump to.
Maybe related: atom/symbols-view#95

Implement go-to-definition

---

lib/definitions-view.coffee

This simplifies the code a bit as Atom already provides an API to make a path relative.

Use Atom's relativizePath API

---

lib/completion.py

Do not use snippets after import statements

---

lib/completion.py
lib/main.coffee
lib/provider.coffee
package.json
spec/provider-spec.coffee

[WIP] Autocomplete function arguments inside of functions

---

README.md

Clarify documentation for virtualenvs

---

lib/provider.coffee
lib/scope-helpers.coffee
package.json

Ignore args completion inside of strings

---

lib/completion.py
lib/main.coffee
lib/provider.coffee

Make fuzzy matcher optional

---

lib/completion.py
lib/main.coffee
lib/provider.coffee
package.json

Fuzzy Matcher Improvements

---

lib/completion.py

Recursively look for top definition

---

README.md
lib/interpreters-lookup.coffee
lib/main.coffee

This is a simple way to handle virtualenvwrapper for me

Add $PROJECT_NAME variable support to simplify virtualenvwrapper support

---

README.md
lib/completion.py
lib/override-view.coffee
lib/provider.coffee

Extremely hacky, but its works somehow.
Closes #178

Add proof-of-concept of method override feature

---

lib/main.coffee

* tracks whether user did fresh install, upgraded or restarted

track `lastEvent`

---

package.json

Adds back relevant `activationHooks`

Add back activation hooks

---

lib/main.coffee

* Check if `atom.packages.hasActivatedInitialPackages` exists before calling
* Re fixes #1

Compatibility fix

---

lib/touchbar.coffee

Closes https://github.com/autocomplete-python/autocomplete-python/issues/318

Don't destructure TouchBar if it doesn't exist

---

README.md
lib/main.coffee
package.json
styles/autocomplete-python.less

Updates the Kite install flow using the [changes in `kite-installer`](https://github.com/kiteco/kite-installer/pull/50) and also removes tracking.
Also updates `README.md` and the settings description when enabling Kite.

Clarify install flow

---

.travis.yml
spec/fixtures/another.py
spec/fixtures/argument-test.py
spec/fixtures/packages/test_pkg/__init__.py
spec/fixtures/test.py
spec/provider-spec.coffee

Fixes existing tests and creates new ones.
Everything except the tests involving `atom.commands.dispatch` work, for some reason, I can't get those to actually run the command. If any future reader can figure out the problem, please let me know.
TODO

[WIP] Tests

---

package.json

Basically a rework of the error reporting system to get messages when install/startup commands fails.

Update kite-installer to v3

---

package.json

Updates dependencies to fix installation error

Fix install error

---

lib/main.coffee
package-lock.json
package.json

Removes email requirement to install Kite

Remove email requirement
