lib/completion.py
lib/main.coffee

Hi. Since we have to enable parameters completion (aka "Complete with snippets") to get auto add brackets (#26), I've decided to make an option to choose between none, all parameters and only required.
Well this is the first time that I mess with Atom, I hope that I haven't broken anything.

Include an option to complete only required params

---

lib/completion.py

The package do not work when current file is in a path with Chinese characters.
The problem is because the encoding of sys.stdin is set to 'GBK' however the acuatually encoding is 'utf-8'.  
I did some fix and it works for me.

fix bug when current file is in non-english path

---

lib/completion.py
lib/definitions-view.coffee

Relative paths will be used when referring to files within `$PROJECT`. I think it makes the definition list more readable.

Show relative paths to definitions where possible

---

lib/definitions-view.coffee
lib/provider.coffee

Also fixed a bug that caused focus to be lost when the definition list was cancelled.

Immediately show definition if only one matches

---

lib/completion.py
lib/provider.coffee
spec/provider-spec.coffee

This changes a number of things:
* snippets are always used but their brevity can be adjusted as usual
* right column is only displayed for constants (other types have icons that indicate their type)
* call signature is always displayed instead of docstrings as lack of formatting makes docstring unreadable (also removed the setting allowing to hide it as it is always useful)

Remove redundant information

---

lib/completion.py
lib/main.coffee
lib/provider.coffee
package.json
spec/provider-spec.coffee

Idea is to autocomplete function arguments only when you type a bracket.
It is done with simple `editor.insertText` thus many bugs could occur. Snippet is not formatted.
#83 #87

[WIP] Autocomplete function arguments on bracket

---

lib/completion.py
lib/provider.coffee
package.json
spec/provider-spec.coffee

Also added trailing `=` after non-keyword arguments as the only reason to complete I can think of is to pass them as keyword args.

Implement fuzzy filtering, treat args as variables

---

lib/completion.py
lib/main.coffee
lib/provider.coffee

* Throw error only once if python executable not found
* Attempt to restart daemon if process were killed (closes #32)
* Fixed python’s exceptions output
* No more errors about closed socket
* Use predefined values for python executable name setting
The best thing is that if you have PATH problems – you will not be annoyed with thousands of errors anymore.

Use Atom's BufferedProcess for better daemon management

---

README.md
lib/hyperclickProvider.coffee
lib/main.coffee
lib/provider.coffee
package.json

[Hyperclick](https://atom.io/packages/hyperclick) can use autocomplete-python as one of providers. 
Click on anything while holding CMD to trigger go-to-definition.
@eMerzh check this out, as this was your idea.

[WIP] Add hyperclick support for go-to-definition

---

keymaps/autocomplete-python.cson

I'm using `python-tools` with this package. I think this is why I cannot use shortcut.
What I did is I found that the grammer is detected as `source python django` so I've added the following to my `keymap.cson`:
'.platform-linux atom-text-editor[data-grammar*="source python"]:not(.mini)':
'ctrl-alt-g': 'autocomplete-python:go-to-definition'
And it worked.
Therefore I'm contributing this change.

Support `source python django` in the grammer

---

README.md
lib/provider.coffee
lib/rename-view.coffee
lib/usages-view.coffee
package.json

Trying to think about which features we can implement to help with refactoring.
With this https://github.com/atom/atom/pull/10178 we should be able to open pending tabs programatically, thus show & close usages in different files as you scroll. Could be useful if you are looking for something. It is already implemented for single file. *This is different from go-to-definition.*
Another important feature – smart rename within project. This is something I need to think about. It definitely should be done in Atom side. We already have list of all files with each token to be renamed.

Advanced show usages features

---

lib/completion.py
lib/main.coffee
lib/provider.coffee
package.json
styles/autocomplete-python.less

We can get a docstring of object which is currently under a cursor using go to definition.
Another option is to only lookup for docstrings when you select entire object name.
But probably lookup of each object under a cursor should be ok. Need to limit the scopes so we will not call it on non-related stuff.
Another option is to only activate it on specific command call.
https://atom.io/docs/api/v1.5.3/Cursor#instance-onDidChangePosition
Closes #181
https://github.com/atom/atom/issues/9936

[WIP] Show related docstrings in message panel

---

lib/provider.coffee

- editor.displayBuffer deprecated since Atom v1.8.0
fixes #221

Fix deprecation in provider.coffee

---

package.json

Fixes #195 by not activating the package until the user actually opens a
Python file.
This saves me about 100ms of Atom startup time whenever I don't edit Python.
For more details, search for `activationHooks` on
http://flight-manual.atom.io/hacking-atom/sections/package-word-count/

Delay activation until needed

---

package.json

Updates `kite-installer` to v0.4.8, which is compatible with older JS engines/versions of atom
Fixes #1

Compatibility

---

lib/main.coffee

The check of `@provider.lastSuggestions ` at main.coffee:356 fixes #278 for me. I also found another unprotected access at line 318 that I have changed as well. The traceback in that particular issue leads to line 305
I looked at changing accesses to `@provider.lastSuggestions` to return an empty list rather than, but I'm not really familiar with coffeescript and couldn't figure out how it was defined. That may be a cleaner solution as you wouldn't have to check all accesses to it.

Fix #278 - Unprotected access of @provider.lastSuggestions

---

lib/hyperclick-provider.coffee

This fixes #307 which happens when hyperclick is used before doing any completion.

Load provider before trying to go to definition

---

lib/interpreters-lookup.coffee

When the interpreter path does not contain `$PROJECT` or `$PROJECT_NAME`, it should be included even if no project is loaded.
Should fix #259.

fix variable substitution for interpreter path

---

README.md
lib/main.coffee
package.json

This PR updates the `kite-installer` dependency to the latest version. It includes the following changes:
1. More robust and tested API to handle Kite state changes
2. Updates to copy - specifically, it makes clear on the first step that Jedi will be installed no matter which engine the user chooses

Use new Kite install flow

---

lib/hyperclick-provider.coffee

In latest Atom + Python grammar, function calls like `foo()` are given an `entity.name` scope, so are excluded from hyperclick suggestions. This removes the scope from `disableForSelector` option.
Appears to fix #370 for me, locally.

Don't disable hyperclick at entity.name scope fixes #370

---

lib/main.coffee
package.json

Previously an error would occur if a non-admin user attempted to install Kite. This PR incorporates a change from `kite-installer` that prevents this error from occurring.

Fix install for non-admin users

---

lib/jedi/parser/grammar3.7.txt

Copy `grammar3.6.txt` to `grammar3.7.txt` to support Python 3.7. Without a grammar file for Python 3.7, Jedi autocompletion silently fails.

Update Jedi with fix for Python 3.7

---

lib/completion.py

Coming from https://github.com/brennv/autocomplete-python-jedi/commit/44e24b1ff710427b2da091ce5f7a0a7e36782dab
"
Exit the completion process on EOF
The real problem is that `BufferedProcess.kill` is *asynchronous* on
Windows and Atom exits before it gets a chance to complete. So the
process is left alive, and it ignores EOF and just keeps trying to read
in an infinite loop.
"
Fixes https://github.com/autocomplete-python/autocomplete-python/issues/310
And probably https://github.com/autocomplete-python/autocomplete-python/issues/301

Exit the completion process on EOF

---

lib/provider.coffee

This PR fixes the situation where both Kite and autocomplete-python are active and the "Automatically Confirm Single Suggestion" setting from autocomplete-plus is enabled. Previously, this combination would result in snippets being inserted automatically into the buffer without user interaction. This PR prevents that by letting autocomplete-python defer to Kite when completions are triggered.

Stop auto-inserting completions

---

lib/provider.coffee

Resolves https://github.com/kiteco/kiteco/issues/9885
If Kite's enabled, don't fetch suggestions using Jedi. If Kite is disabled, fall back to Jedi.

Suppress completions if Kite is enabled
